# Lab for Jenkins training
Vagrant.configure("2") do |config|

  
  config.vm.box = "kwilczynski/ubuntu-16.04-docker"
  config.vm.hostname = "jenkins-buider"
  config.vm.network "private_network", ip: "192.169.31.11"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end
  
end

